In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [3]:
df=pd.read_csv('titaniccleaneddata.csv')

In [4]:
print(df.isnull().sum())

Unnamed: 0      0
Survived        0
Pclass          0
Age           177
Fare            0
Sex_female      0
Sex_male        0
dtype: int64

In [5]:
df.fillna(0, inplace=True)

In [23]:
df.head()

   Unnamed: 0  Survived  Pclass   Age     Fare  Sex_female  Sex_male
0           0         0       3  22.0   7.2500           0         1
1           1         1       1  38.0  71.2833           1         0
2           2         1       3  26.0   7.9250           1         0
3           3         1       1  35.0  53.1000           1         0
4           4         0       3  35.0   8.0500           0         1

In [27]:
df.to_csv('titanicfinaldata.csv')

In [7]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [8]:
x_train, x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=42)

In [9]:
x_test

     Unnamed: 0  Pclass   Age     Fare  Sex_female  Sex_male
709         709       3   0.0  15.2458           0         1
439         439       2  31.0  10.5000           0         1
840         840       3  20.0   7.9250           0         1
720         720       2   6.0  33.0000           1         0
39           39       3  14.0  11.2417           1         0
..          ...     ...   ...      ...         ...       ...
433         433       3  17.0   7.1250           0         1
773         773       3   0.0   7.2250           0         1
25           25       3  38.0  31.3875           1         0
84           84       2  17.0  10.5000           1         0
10           10       3   4.0  16.7000           1         0

[179 rows x 6 columns]

In [10]:
model=LogisticRegression()

In [11]:
model.fit(x_train, y_train)

C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [12]:
y_pred=model.predict(x_test)

In [13]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_pred, y_test))

0.776536312849162

In [17]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_pred, y_test))

[[86 21]
 [19 53]]

In [20]:
from sklearn.metrics import f1_score
print(f1_score(y_pred, y_test))

0.726027397260274

In [22]:
from sklearn.metrics import precision_score, recall_score
print('the precise score is',precision_score(y_pred, y_test))
print('the recall score is', recall_score(y_pred, y_test))

the precise score is 0.7162162162162162
the recall score is 0.7361111111111112