In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df=pd.read_csv('Titanic-Dataset.csv')

In [56]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
28.00    25
30.00    25
         ..
24.50     1
0.67      1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [111]:
df.drop(columns=['Cabin', 'SibSp', 'Parch', 'Ticket','Embarked','PassengerId', 'Name'], inplace=True)

In [24]:
df.c

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'Fare'], dtype='object')

In [112]:
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [115]:
df=pd.get_dummies(df, columns=['Sex'], drop_first=False, dtype=int)

In [123]:
df.head()

   Survived  Pclass   Age     Fare  Sex_female  Sex_male
0         0       3  22.0   7.2500           0         1
1         1       1  38.0  71.2833           1         0
2         1       3  26.0   7.9250           1         0
3         1       1  35.0  53.1000           1         0
4         0       3  35.0   8.0500           0         1

In [124]:
df.to_csv('titaniccleaneddata.csv')

In [120]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression

In [122]:
x=df.drop(columms=['Survived'], inplace=True)

SyntaxError: invalid syntax (712603572.py, line 1)

   color
0  black
1   blue
2  green

   color_black  color_blue  color_green
0            1           0            0
1            0           1            0
2            0           0            1